[package]
name = "esp-backtrace"
version = "0.4.0"
edition = "2021"
description = "Bare-metal backtrace support for ESP32"
repository = "https://github.com/esp-rs/esp-backtrace"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
default-target = "riscv32imc-unknown-none-elf"
features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"]

[dependencies]
esp-println = { version = "0.3.0", optional = true, default-features = false }

[features]
esp32c2 = ["esp-println?/esp32c2"]
esp32c3 = ["esp-println?/esp32c3"]
esp32 = ["esp-println?/esp32"]
esp32s2 = ["esp-println?/esp32s2"]
esp32s3 = ["esp-println?/esp32s3"]
panic-handler = ["esp-println"]
exception-handler = ["esp-println"]
print-uart = ["esp-println/uart"]
print-jtag-serial = ["esp-println/jtag_serial"]
print-rtt = ["esp-println/rtt"]
