[package]
name = "esp-backtrace"
version = "0.1.0"
edition = "2021"
description = "Bare-metal backtrace support for ESP32"
repository = "https://github.com/esp-rs/esp-backtrace"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"]

[dependencies]
esp-println = { version = "0.2.1", optional = true, default-features = false }
riscv = { version = "0.8.0", optional = true }
xtensa-lx-rt = { version = "0.13.0", optional = true }

[features]
esp32c3 = ["esp-println?/esp32c3", "riscv"]
esp32 = ["esp-println?/esp32", "xtensa-lx-rt/esp32"]
esp32s2 = ["esp-println?/esp32s2", "xtensa-lx-rt/esp32s2"]
esp32s3 = ["esp-println?/esp32s3", "xtensa-lx-rt/esp32s3"]
panic-handler = ["esp-println"]
exception-handler = ["esp-println"]
print-uart = ["esp-println/uart"]
print-jtag-serial = ["esp-println/jtag_serial"]
print-rtt = ["esp-println/rtt"]
