on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-riscv:
    name: Check RISC-V
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chip: [esp32c2, esp32c3, esp32c6, esp32h2]
        printer: ["print-rtt", "print-uart"]
        include:
          - chip: esp32c3
            printer: "print-jtag-serial"
          - chip: esp32c6
            printer: "print-jtag-serial"
          - chip: esp32h2
            printer: "print-jtag-serial"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -Zbuild-std=core --target=riscv32imc-unknown-none-elf --features=${{ matrix.chip }},panic-handler,exception-handler,${{ matrix.printer }}

  check-xtensa:
    name: Check Xtensa
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32s2, esp32s3]
        printer: ["print-rtt", "print-uart"]
        include:
          - chip: esp32s3
            printer: "print-jtag-serial"
    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: false
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -Zbuild-std=core --target=xtensa-${{ matrix.chip }}-none-elf --features=${{ matrix.chip }},panic-handler,exception-handler,${{ matrix.printer }}
